import type { CampusMarketApi, AuthSession, LoginInput, RegisterInput, ProfilePatch, ProductQuery, ProductPage, ProductCreateInput, ProductPatch, CreateOrderInput, OrderTransitionInput, ReviewInput, CommentInput } from './contracts';
import type { User, Product, Favorite, Order, Review, Comment, Conversation, ChatMessage, MarketState, ProductStatus } from '../types';
import { ApiError } from './errors';
import { TokenStore } from '../utils/tokenStore';
import { loadState, saveState } from '../utils/storage';
import { buildSeedMarketState, seedUsers } from '../data/seed';
import { uid } from '../utils/id';
import { fromCanonicalStatus } from './mapper';
interface MockDatabase { users: User[]; market: MarketState; idempotency: Record<string, Order> }
const DB_KEY = 'mock_database_v1';
export class MockCampusMarketApi implements CampusMarketApi {
  private readonly tokenStore: TokenStore; private db: MockDatabase;
  constructor(tokenStore = new TokenStore()) { this.tokenStore = tokenStore; this.db = loadState<MockDatabase>(DB_KEY, { users: seedUsers.map((user) => ({ ...user })), market: buildSeedMarketState(), idempotency: {} }); saveState(DB_KEY, this.db) }
  private persist(): void { saveState(DB_KEY, this.db) }
  private currentUser(): User { const id = this.tokenStore.getAccessToken(); const user = this.db.users.find((item) => item.id === id); if (!user) throw new ApiError({ code: 401, message: '请先登录' }); return user }
  private session(user: User): AuthSession { const expires = new Date(Date.now() + 7 * 86400000).toISOString(); this.tokenStore.set({ accessToken: user.id, expiresAtIso: expires }); return { accessToken: user.id, expiresAtIso: expires, user: { ...user } } }
  async getUser(id: string): Promise<User> { const u=this.db.users.find(u=>u.id===id); if(!u) throw new Error('用户不存在'); const {password,...safe}=u; return safe }
  async listMeetingPoints() { return ['东校区','西校区','南校区','北校区'].map(campus=>({id:campus+'-library',campus:campus as User['campus'],name:'图书馆门口'})) }
  async markConversationRead(_id: string) {}
  async login(input: LoginInput): Promise<AuthSession> { const account = input.account.trim(); const user = this.db.users.find((item) => item.account === account || item.contact === account); if (!user) throw new ApiError({ code: 404, message: '账号不存在，请先注册' }); if (user.password !== input.password) throw new ApiError({ code: 401, message: '密码错误，请重新输入' }); return this.session(user) }
  async register(input: RegisterInput): Promise<AuthSession> { const account = input.account.trim(); if (!account || !input.password || input.password.length < 6 || !input.nickname.trim()) throw new ApiError({ code: 400, message: '请完善注册信息，密码至少 6 位' }); if (this.db.users.some((user) => user.account === account)) throw new ApiError({ code: 409, message: '该账号已注册，请直接登录' }); const user: User = { id: uid('u'), account, password: input.password, nickname: input.nickname.trim(), avatar: `https://picsum.photos/seed/${encodeURIComponent(account)}/200/200`, campus: input.campus, contact: input.contact?.trim() || account, createdAt: Date.now() }; this.db.users.push(user); this.persist(); return this.session(user) }
  async getCurrentUser(): Promise<User | null> { const id = this.tokenStore.getAccessToken(); return this.db.users.find((user) => user.id === id) ?? null }
  async updateProfile(patch: ProfilePatch): Promise<User> { const current = this.currentUser(); Object.assign(current, patch); this.persist(); return { ...current } }
  async logout(): Promise<void> { this.tokenStore.clear() }
  async listProducts(query: ProductQuery): Promise<ProductPage> { const keyword = query.keyword?.trim().toLowerCase() ?? ''; let items = this.db.market.products.filter((p) => (!keyword || `${p.title} ${p.description}`.toLowerCase().includes(keyword)) && (!query.category || p.category === query.category) && (!query.campus || p.campus === query.campus) && (!query.condition || p.condition === query.condition) && (query.minPrice === undefined || p.price >= query.minPrice) && (query.maxPrice === undefined || p.price <= query.maxPrice)); items = [...items].sort((a, b) => query.sort === 'priceAsc' ? a.price - b.price : query.sort === 'priceDesc' ? b.price - a.price : query.sort === 'views' ? b.views - a.views : b.createdAt - a.createdAt); const page = Math.max(1, query.page); const pageSize = Math.max(1, query.pageSize); return { items: items.slice((page - 1) * pageSize, page * pageSize), page, pageSize, total: items.length } }
  async getProduct(id: string): Promise<Product> { const product = this.db.market.products.find((item) => item.id === id); if (!product) throw new ApiError({ code: 404, message: '商品不存在' }); return { ...product } }
  async createProduct(input: ProductCreateInput): Promise<Product> { const user = this.currentUser(); const product: Product = { ...input, id: uid('p'), sellerId: user.id, status: '在售', views: 0, createdAt: Date.now(), images: input.images.length ? input.images : [`https://picsum.photos/seed/${uid('image')}/600/600`], contact: input.contact ?? user.contact }; this.db.market.products.unshift(product); this.persist(); return { ...product } }
  async updateProduct(id: string, patch: ProductPatch): Promise<Product> { const user = this.currentUser(); const product = this.db.market.products.find((item) => item.id === id); if (!product) throw new ApiError({ code: 404, message: '商品不存在' }); if (product.sellerId !== user.id) throw new ApiError({ code: 403, message: '无权修改该商品' }); Object.assign(product, patch); this.persist(); return { ...product } }
  async setProductStatus(id: string, status: ProductStatus): Promise<Product> { const user=this.currentUser(); const p=this.db.market.products.find(p=>p.id===id && p.sellerId===user.id); if(!p) throw new Error('无权修改'); p.status=status; this.persist(); return {...p} }
  async incrementProductViews(id: string): Promise<void> { const product = await this.getProduct(id); product.views += 1; const target = this.db.market.products.find((item) => item.id === id); if (target) target.views = product.views; this.persist() }
  async listFavorites(): Promise<Favorite[]> { const user = this.currentUser(); return this.db.market.favorites.filter((f) => f.userId === user.id).map((f) => ({ ...f })) }
  async toggleFavorite(productId: string): Promise<boolean> { const user = this.currentUser(); const index = this.db.market.favorites.findIndex((f) => f.userId === user.id && f.productId === productId); if (index >= 0) { this.db.market.favorites.splice(index, 1); this.persist(); return false } const product = this.db.market.products.find((p) => p.id === productId); if (!product) throw new ApiError({ code: 404, message: '商品不存在' }); this.db.market.favorites.unshift({ id: uid('f'), userId: user.id, productId, createdAt: Date.now() }); this.persist(); return true }
  async createOrder(input: CreateOrderInput): Promise<Order> { const user = this.currentUser(); const duplicate = this.db.idempotency[input.idempotencyKey]; if (duplicate) return { ...duplicate }; const product = this.db.market.products.find((p) => p.id === input.productId); if (!product) throw new ApiError({ code: 404, message: '商品不存在' }); if (product.sellerId === user.id) throw new ApiError({ code: 403, message: '不能购买自己的商品' }); if (product.status !== '在售' || this.db.market.orders.some((o) => o.productId === product.id && !['已取消', '已完成'].includes(o.status))) throw new ApiError({ code: 409, message: '商品已被其他订单锁定' }); const now = Date.now(); const order: Order = { id: uid('o'), productId: product.id, buyerId: user.id, sellerId: product.sellerId, price: product.price, status: '待确认', createdAt: now, updatedAt: now }; product.status = '已售出'; this.db.market.orders.unshift(order); this.db.idempotency[input.idempotencyKey] = order; this.persist(); return { ...order } }
  async transitionOrder(id: string, input: OrderTransitionInput): Promise<Order> { const user = this.currentUser(); const order = this.db.market.orders.find((item) => item.id === id); if (!order) throw new ApiError({ code: 404, message: '订单不存在' }); if (user.id !== order.buyerId && user.id !== order.sellerId) throw new ApiError({ code: 403, message: '无权操作该订单' }); const status = fromCanonicalStatus(input.to); const allowed: Record<string, string[]> = { '待确认': ['交易中', '已取消'], '交易中': ['已完成', '已取消'], '已完成': [], '已取消': [] }; if (!allowed[order.status].includes(status)) throw new ApiError({ code: 409, message: '订单状态不允许该转移' }); order.status = status; order.updatedAt = Date.now(); if (status === '已取消') { const product = this.db.market.products.find((item) => item.id === order.productId); if (product?.status === '已售出') { product.status = '在售'; product.soldAt = undefined } } if (status === '已完成') { const product = this.db.market.products.find((item) => item.id === order.productId); if (product) { product.status = '已售出'; product.soldAt = Date.now() } } this.persist(); return { ...order } }
  async listOrders(role: 'buyer'|'seller'|'all'): Promise<Order[]> { const user = this.currentUser(); return this.db.market.orders.filter((o) => role === 'all' || (role === 'buyer' ? o.buyerId === user.id : o.sellerId === user.id)).map((o) => ({ ...o })) }
  async addReview(orderId: string, input: ReviewInput): Promise<Review> { const user = this.currentUser(); const order = this.db.market.orders.find((o) => o.id === orderId); if (!order || (user.id !== order.buyerId && user.id !== order.sellerId)) throw new ApiError({ code: 403, message: '无权评价该订单' }); if (input.rating < 1 || input.rating > 5) throw new ApiError({ code: 400, message: '评分应为 1-5 分' }); const review = { rating: input.rating, comment: input.comment.trim(), createdAt: Date.now() }; if (user.id === order.buyerId) order.buyerReview = review; else order.sellerReview = review; this.persist(); return review }
  async listComments(productId: string): Promise<Comment[]> { return this.db.market.comments.filter((c) => c.productId === productId).sort((a, b) => b.createdAt - a.createdAt).map((c) => ({ ...c })) }
  async addComment(input: CommentInput): Promise<Comment> { const user = this.currentUser(); if (!input.content.trim()) throw new ApiError({ code: 400, message: '留言内容不能为空' }); const comment: Comment = { id: uid('c'), productId: input.productId, userId: user.id, content: input.content.trim(), parentId: input.parentId ?? null, createdAt: Date.now() }; this.db.market.comments.unshift(comment); this.persist(); return { ...comment } }
  async listConversations(): Promise<Conversation[]> { const user = this.currentUser(); return this.db.market.conversations.filter((c) => c.buyerId === user.id || c.sellerId === user.id).sort((a, b) => b.updatedAt - a.updatedAt).map((c) => ({ ...c })) }
  async getOrCreateConversation(productId: string): Promise<Conversation> { const user = this.currentUser(); const product = await this.getProduct(productId); if (product.sellerId === user.id) throw new ApiError({ code: 400, message: '不能与自己的商品创建会话' }); const found = this.db.market.conversations.find((c) => c.productId === productId && c.buyerId === user.id); if (found) return { ...found }; const now = Date.now(); const conversation: Conversation = { id: uid('conv'), productId, buyerId: user.id, sellerId: product.sellerId, createdAt: now, updatedAt: now }; this.db.market.conversations.unshift(conversation); this.persist(); return { ...conversation } }
  async listMessages(conversationId: string): Promise<ChatMessage[]> { const user = this.currentUser(); const c = this.db.market.conversations.find((item) => item.id === conversationId); if (!c || (c.buyerId !== user.id && c.sellerId !== user.id)) throw new ApiError({ code: 403, message: '无权查看该会话' }); return this.db.market.messages.filter((m) => m.conversationId === conversationId).sort((a, b) => a.createdAt - b.createdAt).map((m) => ({ ...m })) }
  async sendMessage(conversationId: string, content: string): Promise<ChatMessage> { const user = this.currentUser(); await this.listMessages(conversationId); const message: ChatMessage = { id: uid('m'), conversationId, senderId: user.id, content: content.trim(), createdAt: Date.now() }; this.db.market.messages.push(message); const c = this.db.market.conversations.find((item) => item.id === conversationId); if (c) c.updatedAt = message.createdAt; this.persist(); return { ...message } }
  async getUnreadCount(): Promise<number> { const user = this.currentUser(); const convs = await this.listConversations(); return convs.filter((c) => { const messages = this.db.market.messages.filter((m) => m.conversationId === c.id); const last = messages[messages.length - 1]; return Boolean(last && last.senderId !== user.id) }).length }
}
